version: "3"

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db

  redis:
      image: redis:alpine

  celery_worker:
      build:
          context: .
          dockerfile: Dockerfile
      volumes:
          - ./:/app
      command: celery -A roksi_shop worker -l info
      depends_on:
          - db
          - redis
          - backend
      restart: on-failure
      env_file:
          - .env

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: celery -A roksi_shop beat -l info
    env_file:
      - .env
    depends_on:
      - backend
      - db
      - redis
      - celery_worker
