# fly.toml app configuration file generated for roksi-back on 2024-03-09T12:00:45+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'roksi-back'
primary_region = 'waw'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'

[processes]
  app = 'python -m gunicorn --bind :8000 --workers 1 --threads 8 roksi_shop.wsgi'
  worker = 'celery -A roksi_shop worker -l info'
  beat = 'celery -A roksi_shop beat -l info'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
