# Generated by Django 4.2.9 on 2024-02-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("CARD", "Card"), ("CASH", "Cash")],
                default="CASH",
                max_length=4,
            ),
            preserve_default=False,
        ),
    ]
