# Generated by Django 4.2.9 on 2024-02-24 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_alter_payment_options_payment_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="postal_code",
        ),
    ]
