# Generated by Django 4.2.9 on 2024-02-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0007_remove_order_postal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
