# Generated by Django 4.2.9 on 2024-03-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0008_order_is_paid_order_session_id_delete_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="order",
            name="session_id",
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("paid", "Paid"), ("unpaid", "Unpaid")],
                default="unpaid",
                max_length=6,
            ),
        ),
    ]
