# Generated by Django 4.2.9 on 2024-03-09 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0009_remove_order_is_paid_remove_order_session_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
    ]
